### PR TITLE
User login and registering

### PR DESCRIPTION
**Pull request by shazzatherazza**
Addresses issues #7 and #52. Creating a post now requires users to log in, and posts are linked to users. The new pages aren't very pretty but I'm pretty sure other people have created better designs in different branches.

# NOTE YOU HAVE TO ADD `SECRET_KEY=fewrajifow` in your backend `.env`

### CODE REVIEW

**Comment by noobling** [comment]
Hey thanks for the PR I am busy with work right now I will give you a complete review on the weekend make sure this is a complete PR that can be merged into master and it doesn't break any existing things.

**Comment by noobling** [comment]
There is a bug when you logout it seems to infinitely render until the user is redircted
image

**Comment by noobling** [comment]
@milayue  @Hanchooi you guys can take a look at making the login and signup pages more user friendly

**Comment by shazzatherazza** [comment]
@noobling I've made the changes and fixed the logout bug.

**Comment by Hanchooi** [comment]
@noobling Noted with thanks ! Will be looking into it today.

**Comment by Hanchooi** [comment]
@JKKim98 I will try to modify the the sign in and sign up page with this as reference next week. http://pielink.net/register/

**Comment by frinzekt** [comment]
Hi, I seem to be having issue in PR #82 , with `logout.js` causing the infinite loop bug, and also this error
```
Error: No router instance found.
You should only use "next/router" inside the client side of your app.
```
leading to a failed deployment... I can replicate this by going to `http://localhost:3000/logout` without signing in.

Can you please take a look @shazzatherazza . I might have made a mistake on merging from master to post-search branch?

**Comment by shazzatherazza** [comment]
@frinzekt I updated logout.js. Check out the FixLogout branch and let me know if it's working.

**Pull request merged**
