### PR TITLE
50 home50 life updates

### PR DESCRIPTION
**Pull request by Hanchooi**

### CODE REVIEW

**Comment by noobling** [comment]
@Hanchooi what is the state of this feature I can see `.txt` files do you need help finishing this off?

**Comment by Hanchooi** [comment]
> @Hanchooi what is the state of this feature I can see `.txt` files do you need help finishing this off?

Ah, sorry, ignore the txt files, those can be deleted, place it there for my convenience to refer to the original code.

For the login/sign up page, I changed the appearance only. So far the only error I noticed is the button only.

(when you click the LOGIN/SIGN UP button multiple times, it gets increasingly faded.)

**Comment by frinzekt** [comment]
There's kind of a weird bug in the images name in the `./public/images` folder where the images have a capitalized format, and I tried changing it, but git cannot find the change.  Hence, I can't commit

It works in local, but not in the deployed version.

**Comment by noobling** [comment]
@Hanchooi  please remove unnecessary files

**Comment by JKKim98** [comment]
Good work Han! 

@noobling Han will be away for a while so I removed the files in his stead. Regarding the login button issue, it has been resolved in [another PR](https://github.com/codersforcauses/home2health/pull/84).

**Pull request merged**
